### ISSUE TITLE
Room segmentation crashes when using algorithm 5 (voronoi random field segmentation)

### ISSUE THREAD

**Issue by corot** [ipa320/ipa_coverage_planning#6]
Here: `ipa_room_segmentation/common/src/voronoi_random_field_segmentation.cpp:694`

I tried several maps, and always got the same result.
Stacktrace:
```
#0  0x000055555579e1fa in VoronoiRandomFieldSegmentation::getAdaBoostFeatureVector(std::vector<double, std::allocator<double> >&, Clique&, std::vector<unsigned int, std::allocator<unsigned int> >&, std::vector<unsigned int, std::allocator<unsigned int> >&) (this=0x7fffd19da820, feature_vector=std::vector of length 35, capacity 35 = {...}, clique=..., given_labels=std::vector of length 2, capacity 2 = {...}, possible_labels=std::vector of length 3, capacity 3 = {...}) at /home/jorge/catkin_ws/thorp/src/ipa_coverage_planning/ipa_room_segmentation/common/src/voronoi_random_field_segmentation.cpp:694
#1  0x00005555557a2787 in VoronoiRandomFieldSegmentation::segmentMap(cv::Mat const&, cv::Mat&, int, int, int, std::vector<unsigned int, std::allocator<unsigned int> >&, double, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, double, double, double, double, std::vector<cv::Point_<int>, std::allocator<cv::Point_<int> > >*) (this=0x7fffd19da820, original_map=..., segmented_map=..., epsilon_for_neighborhood=5, max_iterations=150, min_neighborhood_size=4, possible_labels=std::vector of length 3, capacity 3 = {...}, min_node_distance=7, show_results=false, classifier_storage_path="room_segmentation/classifier_models/", classifier_default_path="/home/jorge/catkin_ws/thorp/src/ipa_coverage_planning/ipa_room_segmentation/common/files/classifier_models/", max_inference_iterations=9000, map_resolution_from_subscription=0.05000000074505806, room_area_factor_lower_limit=1.53, room_area_factor_upper_limit=1000000, max_area_for_merging=12.5, door_points=0x7fffffff7da0)
    at /home/jorge/catkin_ws/thorp/src/ipa_coverage_planning/ipa_room_segmentation/common/src/voronoi_random_field_segmentation.cpp:1454
#2  0x00005555556fc1df in RoomSegmentationServer::execute_segmentation_server(boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&) (this=0x7fffffff7d00, goal=...) at /home/jorge/catkin_ws/thorp/src/ipa_coverage_planning/ipa_room_segmentation/ros/src/room_segmentation_server.cpp:486
#3  0x0000555555749e79 in boost::_mfi::mf1<void, RoomSegmentationServer, boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&>::operator()(RoomSegmentationServer*, boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&) const (this=0x7fffffff80e0, p=0x7fffffff7d00, a1=...) at /usr/include/boost/bind/mem_fn_template.hpp:165
#4  0x0000555555746094 in boost::_bi::list2<boost::_bi::value<RoomSegmentationServer*>, boost::arg<1> >::operator()<boost::_mfi::mf1<void, RoomSegmentationServer, boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&>, boost::_bi::rrlist1<boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&> >(boost::_bi::type<void>, boost::_mfi::mf1<void, RoomSegmentationServer, boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&>&, boost::_bi::rrlist1<boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&>&, int) (this=0x7fffffff80f0, f=..., a=...) at /usr/include/boost/bind/bind.hpp:319
#5  0x0000555555740061 in boost::_bi::bind_t<void, boost::_mfi::mf1<void, RoomSegmentationServer, boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&>, boost::_bi::list2<boost::_bi::value<RoomSegmentationServer*>, boost::arg<1> > >::operator()<boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&>(boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&) (this=0x7fffffff80e0, a1=...) at /usr/include/boost/bind/bind.hpp:1306
#6  0x0000555555736475 in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, RoomSegmentationServer, boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&>, boost::_bi::list2<boost::_bi::value<RoomSegmentationServer*>, boost::arg<1> > >, void, boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&>::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&) (function_obj_ptr=..., a0=...)
    at /usr/include/boost/function/function_template.hpp:159
#7  0x000055555572dcee in boost::function1<void, boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&>::operator()(boost::shared_ptr<ipa_building_msgs::MapSegmentationGoal_<std::allocator<void> > const> const&) const (this=0x7fffffff80d8, a0=...) at /usr/include/boost/function/function_template.hpp:759
#8  0x0000555555720811 in actionlib::SimpleActionServer<ipa_building_msgs::MapSegmentationAction_<std::allocator<void> > >::executeLoop() (this=0x7fffffff7f20)
    at /opt/ros/melodic/include/actionlib/server/simple_action_server_imp.h:385
#9  0x000055555576628d in boost::_mfi::mf0<void, actionlib::SimpleActionServer<ipa_building_msgs::MapSegmentationAction_<std::allocator<void> > > >::operator()(actionlib::SimpleActionServer<ipa_building_msgs::MapSegmentationAction_<std::allocator<void> > >*) const (this=0x555556014d98, p=0x7fffffff7f20) at /usr/include/boost/bind/mem_fn_template.hpp:49
#10 0x00005555557645a3 in boost::_bi::list1<boost::_bi::value<actionlib::SimpleActionServer<ipa_building_msgs::MapSegmentationAction_<std::allocator<void> > >*> >::operator()<boost::_mfi::mf0<void, actionlib::SimpleActionServer<ipa_building_msgs::MapSegmentationAction_<std::allocator<void> > > >, boost::_bi::list0>(boost::_bi::type<void>, boost::_mfi::mf0<void, actionlib::SimpleActionServer<ipa_building_msgs::MapSegmentationAction_<std::allocator<void> > > >&, boost::_bi::list0&, int) (this=0x555556014da8, f=..., a=...) at /usr/include/boost/bind/bind.hpp:259
#11 0x00005555557603c6 in boost::_bi::bind_t<void, boost::_mfi::mf0<void, actionlib::SimpleActionServer<ipa_building_msgs::MapSegmentationAction_<std::allocator<void> > > >, boost::_bi::list1<boost::_bi::value<actionlib::SimpleActionServer<ipa_building_msgs::MapSegmentationAction_<std::allocator<void> > >*> > >::operator()() (this=0x555556014d98) at /usr/include/boost/bind/bind.hpp:1294
#12 0x000055555575bdca in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, actionlib::SimpleActionServer<ipa_building_msgs::MapSegmentationAction_<std::allocator<void> > > >, boost::_bi::list1<boost::_bi::value<actionlib::SimpleActionServer<ipa_building_msgs::MapSegmentationAction_<std::allocator<void> > >*> > > >::run() (this=0x555556014be0)
    at /usr/include/boost/thread/detail/thread.hpp:116
#13 0x00007ffff598abcd in  () at /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1
#14 0x00007ffff57616db in start_thread (arg=0x7fffd19dc700) at pthread_create.c:463
#15 0x00007ffff446688f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by ipa-foj** [comment]
Hello, could you tell what exactly you are executing? Also as this line is calling an OpenCV function and is switching between versions at that point could you check your OpenCV version and paste it here s.t. we can investigate further?

**Comment by corot** [comment]
Hi, I'm trying the current code with melodic. No changes from my side other than changing the segmentation algorithm to 5 and commenting some of the maps to test to reproduce the crash with several of your test maps (all I tried crashed).

I launch:
```
roslaunch ipa_room_segmentation room_segmentation_action_server.launch
roslaunch ipa_room_segmentation room_segmentation_action_client.launch
```
I use OpenCV 3.2, so the line that crashes is:
```
room_boost_->predict(featuresMat, weaker);
```
But I have zero experience with this part of boost.

**Comment by corot** [comment]
I have found a fork that addresses the issue: https://github.com/Sushant-Chavan/autopnp/tree/kinetic
But still, training voronoi random field crashes.
